spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/services_project?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
  mail:
    host: smtp.gmail.com
    password: cspeljtimqllsnak
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: contacto.arreglaloya@gmail.com
  thymeleaf:
    cache: 'false'
  main:
    banner-mode: 'off'
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 590418585274-918265bn0c4breudkmhnsa0duv7rh5cu.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
